### ISSUE TITLE
Unable to update Centos7 to Almalinux8 on OpenVZ 7 VPS

### ISSUE THREAD

**Issue by centriohost** [cpanel/elevate#106]
In Stage 3 it stopped with bellow error in OpenVZ7 Virtualization platform (VZ)

* 07-23:37:28 (3338) [INFO]
* 07-23:37:28 (3338) [INFO] ============================================================
* 07-23:37:28 (3338) [INFO]                            ERRORS
* 07-23:37:28 (3338) [INFO] ============================================================
* 07-23:37:28 (3338) [INFO]
* 07-23:37:28 (3338) [INFO] 2022-07-07 23:34:46.623903 [ERROR] Actor: source_boot_loader_scanner
* 07-23:37:28 (3338) [INFO] Message: Failed to call `grubby` to list available boot entries.
* 07-23:37:28 (3338) [INFO] Summary:
* 07-23:37:28 (3338) [INFO]     Details: Command ['grubby', '--info', 'ALL'] failed with exit code 1.
* 07-23:37:28 (3338) [INFO]     Stderr:
* 07-23:37:28 (3338) [INFO]
* 07-23:37:28 (3338) [INFO] ============================================================
* 07-23:37:28 (3338) [INFO]                        END OF ERRORS
* 07-23:37:28 (3338) [INFO] ============================================================
* 07-23:37:28 (3338) [INFO]
* 07-23:37:28 (3338) [INFO]
* 07-23:37:28 (3338) [INFO] Debug output written to /var/log/leapp/leapp-upgrade.log
* 07-23:37:28 (3338) [INFO]
* 07-23:37:28 (3338) [INFO] ============================================================

Please review the issue and fix it. Because we are having lot of clients using Centos7 with their cPanel platform.

**Comment by sloanebernstein** [comment]
Hello,

The issue is that both the upstream of our script, namely the AlmaLinux [ELevate](https://almalinux.org/elevate) project, and its own upstream, Red Hat's [Leapp](https://github.com/oamg/leapp) framework, do not appear to be looking to support OpenVZ and similar container-based images, at least at the current time.

**If you are completely certain that the OpenVZ container with which you are testing can be restored from backup in full or is otherwise expendable**, something we can have you try is removing or patching the module which is causing the error. Please let us know if this you are willing to experiment in this way, as we do not know whether this error is hiding a more serious issue preventing container-based systems from being upgraded without significant downtime or data loss.

**Comment by sloanebernstein** [comment]
After contacting the upstream project, I've found out that what I had planned will not be successful, as containerized systems like OpenVZ would need an entirely different mechanism to perform certain critical operations after the point at which the upgrade is currently failing.

Such a mechanism is not currently planned, so this script will not be able to work in your case at this time. I am working with the upstream project to have this information documented publicly. However, it is possible that this may change in the future.

If our script and the upstream projects on which it depends are still not able to handle an in-place upgrade before CentOS 7 becomes End-of-Life, cPanel servers and their accounts should be migrated to another system container running a supported operating system and cPanel using the [Transfer Tool](https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-transfer-accounts-and-configurations-between-cpanel-servers/).

If you have any questions not related to the ELevate script, please contact [cPanel Technical Support](https://cpanel.net/support/) for further assistance.
