### ISSUE TITLE
The system detected the following issues which would prevent cPanel ELevate from upgrading the system to AlmaLinux 8

### ISSUE THREAD

**Issue by maisondasilva** [cpanel/elevate#119]
Cloud KVM CentOS v7.9.2009 STANDARD kvm

One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8. Please remove these packages before continuing the update. - ea-openssl-devel - ea-php74-php-ioncube12 - ea-php81-php-ioncube12

**Comment by atoomic** [comment]
please try to remove these packages and rerun the elevate script
```
rpm -e --nodeps ea-openssl-devel ea-php74-php-ioncube12 ea-php81-php-ioncube12
```

**Comment by maisondasilva** [comment]
> please try to remove these packages and rerun the elevate script
> 
> ```
> rpm -e --nodeps ea-openssl-devel ea-php74-php-ioncube12 ea-php81-php-ioncube12
> ```

Will the ea-openssl-devel package be installed later? About the Ioncube I need it, will it be installed later?

**Comment by atoomic** [comment]
Note you will be able to reinstall these packages (the name or version is different)
* ea-openssl11-devel
* ea-php74-php-ioncube11

The following packages are currently not available
* ea-php81-php-ioncube

**Comment by atoomic** [comment]
The `ea-openssl[-devel]` packages on CentOS 7 are for ea-php5 (old versions of php).
AlmaLinux 8 uses `ea-openssl11[-devel]` packages instead.

Also note, rather than removing the package manually it's recommended to remove the unsupported profile(s)/package(s) from the WHM UI by disabling the features using these packages.

The AlmaLinux 8 EA4 repo also provides: `ea-php81-php-ioncube12` (contrary to my previous message)
```
Name         : ea-php81-php-ioncube12
Version      : 12.0.1
Release      : 2.2.1.cpanel
Architecture : x86_64
Size         : 426 k
Source       : ea-php81-php-ioncube12-12.0.1-2.2.1.cpanel.src.rpm
Repository   : EA4
Summary      : v12 Loader for ionCube-encoded PHP files
URL          : http://www.ioncube.com/loaders.php
License      : Redistributable
Description  : The v12 ionCube Loader enables use of ionCube-encoded PHP files running
             : under PHP 8.1.
```

**Comment by maisondasilva** [comment]
In this case can I remove the packages via EA4 and after installed Alma Linux i can activate the correct packages with EA4, correct?

**Comment by toddr** [comment]
@maisondasilva , Not all features are available in 8 that were available in 7. There are 2 classes of not available.
1. The package was needed in 7 but can revert to using the distro package in 8.
2. The package is not available, usually because the software is old enough that it doesn't or shouldn't be built/used on 8.

- openssl comes from the distro in 8.
- We believe you'll be able to re-install the ioncube packages. They only recently became available in EA4 for 8.

**Comment by toddr** [comment]
@maisondasilva how did your upgrade go?

**Comment by toddr** [comment]
closing case due to lack of response. please re-open this case if you need further assistance!
