### ISSUE TITLE
Cloudlinux 7?

### ISSUE THREAD

**Issue by chrisduk112** [cpanel/elevate#191]
Hi
we upgraded all of our servers to cPanel 108 and now it shows elvate from CloudLinux 7 to Almalinux, i thought this was only going to show on centos?? 

Until CL7 > CL8 is available I suggest this doesn't show on CloudLinux installs.

**Comment by toddr** [comment]
Apologies. We do not support cloudlinux at this time (coming soon!). When it is available, the upgrade path will be from CL7 to CL8.

**Comment by sloanebernstein** [comment]
Hello,

There are several mechanisms which can inform the administrator about ELevate:

* There are banners on the main WHM page after login.
* The Security Advisor runs a check during nightly maintenance, and it could be informing you as configured in the Contact Manager.
* A manual run of the Security Advisor through WHM also reports eligibility for ELevate, though only through the graphical interface and not using the Contact Manager.

Which ones are you encountering?

**Comment by chrisduk112** [comment]
There are banners on the main WHM page after login.

^^ this one.

**Comment by sloanebernstein** [comment]
Hello,

This ends up being a bug in cPanel itself, rather than ELevate. It's being fixed as CPANEL-42362, which will show up in the [108 ChangeLog](https://docs.cpanel.net/changelogs/108-change-log/) once that is fixed. As such, I'm closing this issue here as resolved. Thank you for reporting this anyway.
