### ISSUE TITLE
Server unbootable after stage 4 of 5 (cpanel elevate)

### ISSUE THREAD

**Issue by lucaslim86** [cpanel/elevate#256]
Hi cpanel,

I am performing cpanel elevate on my centos 7 server to upgrade to almalinux 8.
Before performing the upgrade, I have removed all known blockers and it was all cleared.

Once I started the upgrade via SSH. Everything is going smoothly without errors.
After stage 4. It say it will now reboot the server.
However the server never came back online.

I look into this issue under cpanel elevate github. It look very similar to this case:
https://github.com/cpanel/elevate/issues/215

I am not able to create ticket at cpanel because I can't access Support Access ID
Server IP: 94.156.33.145
Please email me at lucas_lim@outlook.com

Regards,
Lucas

**Comment by atoomic** [comment]
The main elevation process occurs at the end of `stage 3`.

Once you reach `stage 4` you should already be on AlmaLinux 8.
`stage 4` is updating the `cpanel` product to match the new Operating System.

How long occurred since you cannot access the server? 
Is it possible that it's still performing the update?
Do you have a way to access to a remote console as backup?

In case #215 customer was able to access to WHM and use the terminal feature from the UI.

In order to get support from cPanel, please open a support ticket. You can read more about requesting support from
https://docs.cpanel.net/knowledge-base/technical-support-services/how-to-open-a-technical-support-ticket/
