### ISSUE TITLE
[BUG] PostgreSQL meant to upgrade (9.2 -> 10) but is failed and unstartable post-ELevate

### ISSUE THREAD

**Issue by lsthompson** [cpanel/elevate#485]
**Describe the bug**
When checking if ELevate is safe to run, it reports that PostgreSQL 9.2 exists and will be one-way upgraded to v10:

```
* 2024-07-27 21:02:18 [WARN] You have postgresql-server version 9.2 installed. 
This will be upgraded irreversibly to version 10.0 when you switch to CloudLinux 8
```

However when the ELevate job is complete, it leaves PostgreSQL broken. Automatic restart-fix does not work. 

Manual attempt:

```
Jul 29 21:42:35 SQL systemd[1]: Starting PostgreSQL database server...
Jul 29 21:42:35 SQL postgresql-check-db-dir[135060]: An old version of the database format was found.
Jul 29 21:42:35 SQL postgresql-check-db-dir[135060]: Use 'postgresql-setup --upgrade' to upgrade to version '10'
Jul 29 21:42:35 SQL postgresql-check-db-dir[135060]: See /usr/share/doc/postgresql/README.rpm-dist for more information.
Jul 29 21:42:35 SQL systemd[1]: postgresql.service: Control process exited, code=exited status=1
Jul 29 21:42:35 SQL systemd[1]: postgresql.service: Failed with result 'exit-code'.
Jul 29 21:42:35 SQL systemd[1]: Failed to start PostgreSQL database server.
```

So we try that, have to install a package, try again, then it fails too:

```
$ postgresql-setup --upgrade
ERROR: Please install the postgresql-upgrade package.
$ yum install postgresql-upgrade -y
$ postgresql-setup --upgrade
 * Upgrading database.
ERROR: pg_upgrade tool failed
ERROR: Upgrade failed.
 * See /var/lib/pgsql/upgrade_postgresql.log for details.
```

That log file contains:

```
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok

*failure*
Consult the last few lines of "pg_upgrade_server.log" for
the probable cause of the failure.

connection to database failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/lib/pgsql/.s.PGSQL.5432"?

could not connect to source postmaster started with the command:
"/usr/lib64/pgsql/postgresql-9.2/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/var/lib/pgsql/data-old" -o "-p 5432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directory='/var/lib/pgsql'" start
Failure, exiting
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Have PostgreSQL 9.x installed on machine to-be-elevated.
2. Upgrade via ELevate to RHEL v8 derivative as normal.
3. PostgreSQL cannot start nor be upgraded.

**Expected behavior**
It should do as mentioned, and successfully upgrade PostgreSQL to v10.

**Comment by toddr** [comment]
We currently block elevate upgrades if Postgresql is installed. What version of elevate did you use? ```/scripts/elevate-cpanel --version```

**Comment by lsthompson** [comment]
Version 49 reported.

**Comment by toddr** [comment]
However, we only block it if you have customer databases installed. Which active databases did you have in the 9.x version?

**Comment by lsthompson** [comment]
> Which active databases did you have in the 9.x version?

None that I can see. Safe to remove per normal then?

**Comment by toddr** [comment]
yep.

**Comment by sloanebernstein** [comment]
A note after the fact:

The reason `postgresql-setup --upgrade` fails is due to a bug in the `postgresql-upgrade` package AlmaLinux 8 inherited from RHEL. Specifically, the EL7 package used by CentOS 7 applies a custom patch that backports from 9.3 into 9.2 the ability to specify multiple Unix socket locations as `unix_socket_directories` instead of a single location with `unix_socket_directory`. In the EL8 version of the package used by AlmaLinux 8, the minimal version of PostgreSQL 9.2 built to allow `postgresql-setup --upgrade` to function does not apply this additional patch. Therefore, PostgreSQL 9.2 does not recognize the directive in its configuration file, which it considers to be a fatal error, preventing the upgrade from working.

The workaround is to change `unix_socket_directories` to `unix_socket_directory` just before running `postgresql-setup --upgrade`. This is reflected in [the example set of instructions we provide in the Blockers page of our documentation](https://cpanel.github.io/elevate/blockers/#updating-the-postgresql-data-directory-after-elevation).
