### ISSUE TITLE
Terminal output still sometimes reporting elevate is canceled.

### ISSUE THREAD

**Issue by neryskistner** [cpanel/elevate#69]
The issue reported in https://github.com/cpanel/elevate/issues/46 and addressed in https://github.com/cpanel/elevate/pull/67 still is happening:

```
* 29-18:40:42 (1130) [INFO] ******************************************************************************************
* 29-18:40:42 (1131) [INFO] *
* 29-18:40:42 (1132) [INFO] * Starting stage 1 of 5: Installing elevate-cpanel.service service
* 29-18:40:42 (1133) [INFO] *
* 29-18:40:42 (1134) [INFO] ******************************************************************************************
* 29-18:40:42 (2981) [INFO] Installing service elevate-cpanel.service which will upgrade the server to AlmaLinux 8
* 29-18:40:42 (3099) [INFO] Running: /usr/bin/systemctl daemon-reload


* 29-18:40:43 (3099) [INFO] Running: /usr/bin/systemctl enable elevate-cpanel.service

Created symlink from /etc/systemd/system/multi-user.target.wants/elevate-cpanel.service to /etc/systemd/system/elevate-cpanel.service.

* 29-18:40:43 (3014) [INFO] Starting service elevate-cpanel.service
* 29-18:40:43 (280) [INFO] # Monitoring existing upgrade (stage=2) process via: tail -f /var/log/elevate-cpanel.log
* 29-18:40:43 (3099) [INFO] Running: /usr/bin/systemctl start elevate-cpanel.service

Job for elevate-cpanel.service canceled.
Connection to 10.2.70.15 closed by remote host.
Connection to 10.2.70.15 closed.
```
What is noticeably different too is that it is no longer reporting that it is booting into stage 3 anymore. It just starts the reboot, sometimes after reporting that the `elevate-cpanel.service` job is canceled.

**Comment by sloanebernstein** [comment]
I think that the `Job for elevate-cpanel.service canceled.` message is coming from systemd itself, and it is happening because systemd is, from its perspective, still in the process of setting up the service when something (`elevate-cpanel` itself, in this case) is asking systemd to change to a target which no longer has the `elevate-cpanel.service` active. So instead of calling `/sbin/reboot` from the main process, we should instead (after a reasonable delay) either spawn a new process or ask an existing service to do the reboot for us.
